//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DbgCM.rc
//
#define IDD_SETUP                    100
#define IDD_SETUP_DBG                101
#define IDD_SETUP_TRC                102
#define IDD_SETUP_FD                 103
#define IDD_FDADD                    104
#define IDD_TRACE_REC                105
#define IDD_TRACE_EXC                106
#define IDD_TRACE_CNT                107
#define IDB_LOAD                     110
#define IDI_ICONLIST1                111
#define IDI_ICONLIST2                112
#define IDI_ICONLIST3                113
#define IDC_BITMAP                   1000
#define IDC_CONFIG_UNIT              1001
#define IDC_CONFIG_SERNUM            1002
#define IDC_CONFIG_HVERSION          1003
#define IDC_CONFIG_FVERSION          1004
#define IDC_CONFIG_PORT              1005
#define IDC_CONFIG_SWJ               1006
#define IDC_CONFIG_CLK               1007
#define IDC_CONFIG_DEVICE            1008
#define IDC_CONFIG_AP                1009
#define IDC_STATIC_DEVICE            1010
#define IDC_STATIC_TDO               1011
#define IDC_STATIC_TDI               1012
#define IDC_STATIC_ID                1013
#define IDC_STATIC_DEVNAME           1014
#define IDC_STATIC_IRLEN             1015
#define IDC_STATIC_MOVE              1016
#define IDC_STATIC_AP                1017
#define IDC_JTAG_AUTO                1020
#define IDC_JTAG_MANUAL              1021
#define IDC_JTAG_ID                  1022
#define IDC_JTAG_DEVNAME             1023
#define IDC_JTAG_IRLEN               1024
#define IDC_JTAG_UP                  1025
#define IDC_JTAG_DOWN                1026
#define IDC_JTAG_ADD                 1027
#define IDC_JTAG_DELETE              1028
#define IDC_JTAG_UPDATE              1029
#define IDC_CACHE_CODE               1030
#define IDC_CACHE_MEM                1031
#define IDC_CODE_VERIFY              1032
#define IDC_FLASH_LOAD               1033
#define IDC_BOOT_RESET               1034
#define IDC_INIT_RST                 1035
#define IDC_RST_TYPE                 1036
#define IDC_BOOT_RUN                 1037
#define IDC_TRACE_CLOCK              1100
#define IDC_TRACE_ENABLE             1101
#define IDC_ETM_ENABLE               1102
#define IDC_TPIU_CLOCK               1104
#define IDC_TRACE_USE_CORECLK_ENABLE 1105
#define IDC_TRACE_PORT               1110
#define IDC_TRACE_SWO_PRE            1111
#define IDC_TRACE_SWO_AP             1112
#define IDC_TRACE_SWO_CLK            1113
#define IDC_TRACE_SWO_MHZ            1114
#define IDC_TRACE_STATUS             1115
#define IDC_TRACE_TIMESTAMP          1120
#define IDC_TRACE_TS_PRE             1121
#define IDC_TRACE_PCSAMPLE           1130
#define IDC_TRACE_PC_PRE             1131
#define IDC_TRACE_PC_PER             1132
#define IDC_TRACE_PC_DATA            1133
#define IDC_TRACE_CPI                1140
#define IDC_TRACE_EXC                1141
#define IDC_TRACE_LSU                1142
#define IDC_TRACE_SLEEP              1143
#define IDC_TRACE_FOLD               1144
#define IDC_TRACE_EXCTRC             1145
#define IDC_ITM_TE                   1150
#define IDC_ITM_TP                   1151
#define IDC_ITM_TE0                  1152
#define IDC_ITM_TE1                  1153
#define IDC_ITM_TE2                  1154
#define IDC_ITM_TE3                  1155
#define IDC_ITM_TE4                  1156
#define IDC_ITM_TE5                  1157
#define IDC_ITM_TE6                  1158
#define IDC_ITM_TE7                  1159
#define IDC_ITM_TE8                  1160
#define IDC_ITM_TE9                  1161
#define IDC_ITM_TE10                 1162
#define IDC_ITM_TE11                 1163
#define IDC_ITM_TE12                 1164
#define IDC_ITM_TE13                 1165
#define IDC_ITM_TE14                 1166
#define IDC_ITM_TE15                 1167
#define IDC_ITM_TE16                 1168
#define IDC_ITM_TE17                 1169
#define IDC_ITM_TE18                 1170
#define IDC_ITM_TE19                 1171
#define IDC_ITM_TE20                 1172
#define IDC_ITM_TE21                 1173
#define IDC_ITM_TE22                 1174
#define IDC_ITM_TE23                 1175
#define IDC_ITM_TE24                 1176
#define IDC_ITM_TE25                 1177
#define IDC_ITM_TE26                 1178
#define IDC_ITM_TE27                 1179
#define IDC_ITM_TE28                 1180
#define IDC_ITM_TE29                 1181
#define IDC_ITM_TE30                 1182
#define IDC_ITM_TE31                 1183
#define IDC_ITM_TP0                  1184
#define IDC_ITM_TP1                  1185
#define IDC_ITM_TP2                  1186
#define IDC_ITM_TP3                  1187
#define IDC_FLASH_ERASENONE          1200
#define IDC_FLASH_ERASESECT          1201
#define IDC_FLASH_ERASEALL           1202
#define IDC_FLASH_PROGRAM            1203
#define IDC_FLASH_VERIFY             1204
#define IDC_FLASH_RESETRUN           1205
#define IDC_FLASH_RAMSTART           1206
#define IDC_FLASH_RAMSIZE            1207
#define IDC_FLASH_START              1208
#define IDC_FLASH_SIZE               1209
#define IDC_FLASH_ALGLIST            1210
#define ID_ADD                       1220
#define ID_REMOVE                    1221
#define IDC_TRACE_RECLIST            1300
#define IDC_TRACE_RECSCROLL          1301
#define IDC_TRACE_EXCLIST            1310
#define IDC_TRACE_CPICNT             1320
#define IDC_TRACE_EXCCNT             1321
#define IDC_TRACE_SLEEPCNT           1322
#define IDC_TRACE_LSUCNT             1323
#define IDC_TRACE_FOLDCNT            1324
#define IDC_TRACE_CPICLR             1325
#define IDC_TRACE_EXCCLR             1326
#define IDC_TRACE_SLEEPCLR           1327
#define IDC_TRACE_LSUCLR             1328
#define IDC_TRACE_FOLDCLR            1329
#define IDC_ALGOFILE                 1400
#define IDC_TRACE_TS_PRE_LABEL       1400
#define IDC_TRACE_SWO_PRE_           1401
#define IDC_TRACE_SWO_CLK_           1402
#define IDC_EDIT_PDSC_DBGCONF        1421
#define IDC_EDIT_PDSC_PACKID         1422
#define IDC_CHECK_PDSC_DEBUG         1423
#define IDC_RST_VECT_CATCH           1423
#define IDC_CHECK_PDSC_LOG           1424
#define IDC_EDIT_PDSC_LOGFILE        1425
#define IDC_BUTTON_PDSC_DBGCONF_EDIT 1522
#define IDC_STATIC_PDSC_DBGCONF      1523
#define IDR_MENU_TRACE_REC           5000
#define IDD_SETUP_PDSC               5029
#define ID_TRACE_COUNTER             32771
#define ID_TRACE_EXCEPTION           32772
#define ID_TRACE_PCSAMPLE            32773
#define ID_TRACE_ITM                 32774
#define ID_TRACE_DATAREAD            32775
#define ID_TRACE_DATAWRITE           32776

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE 5001
#define _APS_NEXT_COMMAND_VALUE  32782
#define _APS_NEXT_CONTROL_VALUE  1403
#define _APS_NEXT_SYMED_VALUE    5000
#endif
#endif
